### ISSUE TITLE
EISDIR in Swagger Error

### ISSUE THREAD

**Issue by hpxix** [citrineos/citrineos#47]
**Which repository?**
Is it:

- citrineos-core

**Describe the bug**
When you build the docker up the container belonging to swagger doesn't work with the error shown bellow, i tried checking on the "logo" Path over and over and it was fine nothing was wrong with the path.

**To Reproduce**
1. Clone Application
2. cd /server
3. docker compose up --build
4. See error in server-citrine

**Expected behavior**
You're expecting the server-citrine to run just fine on port 0.0.0.0/8080

**Error**
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:744:3)
    at tryReadSync (node:fs:444:20)
    at Object.readFileSync (node:fs:490:19)
    at registerSwaggerUi (/usr/local/apps/citrineos/02_Util/dist/util/swagger.js:130:35)
    at /usr/local/apps/citrineos/02_Util/dist/util/swagger.js:210:9
    at Generator.next (<anonymous>)
    at /usr/local/apps/citrineos/02_Util/dist/util/swagger.js:36:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/apps/citrineos/02_Util/dist/util/swagger.js:32:12)
    at initSwagger (/usr/local/apps/citrineos/02_Util/dist/util/swagger.js:208:12) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

Node.js v18.20.4
npm error Lifecycle script start-docker-cloud failed with error:
npm error Error: command failed
npm error   in workspace: @citrineos/server@1.4.3
npm error   at location: /usr/local/apps/citrineos/Server

**Desktop (please complete the following information):**
 - OS: mac os arm64 Running Ventura 13.5.1
 - Docker
 - Version [3.x]

**Additional context**
The Error persists when Building the /Server container which leads to an error in the Container server-citrine with an ESDIR Error

**Comment by hpxix** [comment]
[FIX]

Ok so if you face this error you might as well do the following to fix it because I've spent endless hours fixing it and surprisingly it was fixed when I updated my docker version to the latest stable version V 4.34.3
