### ISSUE TITLE
npm run seed-db fails [citrineos-ocpi]

### ISSUE THREAD

**Issue by lydiazcheng** [citrineos/citrineos#52]
**Which repository?**

- citrineos-ocpi

**Describe the bug**
`npm run seed-db` doesn't work and throw an error, 
```
ERROR: Error: Error reading "00_Base/src/config/sequalize.bridge.config.js". Error: Error: Cannot find module './ocpi.server.config.ts'
Require stack:
- /citrineos-ocpi/00_Base/src/config/sequalize.bridge.config.js
    at Object.readConfig (/.nvm/versions/node/v16.20.2/lib/node_modules/sequelize-cli/lib/helpers/config-helper.js:92:15)
    at getSequelizeInstance (/.nvm/versions/node/v16.20.2/lib/node_modules/sequelize-cli/lib/core/migrator.js:24:36)
    at getMigrator (/.nvm/versions/node/v16.20.2/lib/node_modules/sequelize-cli/lib/core/migrator.js:42:21)
    at seedAll (/.nvm/versions/node/v16.20.2/lib/node_modules/sequelize-cli/lib/commands/seed.js:26:36)
    at Object.exports.handler (/.nvm/versions/node/v16.20.2/lib/node_modules/sequelize-cli/lib/commands/seed.js:17:13)
```

**To Reproduce**
1. Go to 'citrineos-ocpi'
2. Install all dependencies
3. Execute `npm run seed-db`

**Expected behavior**
Run `npm run seed-db` without any errors and the database are prepared with necessary data entries.

**Desktop (please complete the following information):**
 - OS: Mac as well as Window

**Comment by lydiazcheng** [comment]
A fix is in this PR: https://github.com/citrineos/citrineos-ocpi/pull/161 But there is another error then, `ERROR: Error: Error reading "00_Base\src\config\sequalize.bridge.config.js". Error: ReferenceError: register is not defined`. We need to have a further investigatioin.
