### ISSUE TITLE
unix-init-install-all.sh fails

### ISSUE THREAD

**Issue by agardiol** [citrineos/citrineos#9]
**Describe the bug**
When running unix-init-install-all.sh on Ubuntu 22.04:
```
citrineos-core/50_Server$ ./unix-init-install-all.sh 
48590e3b88f151556378ee7e376eca2efcb9b0d295d2134c6ee3941770398721
Executing: cd 00_Base
Executing: rm -rf ./lib
Executing: rm -f citrineos-base-1.0.0.tgz
Executing: npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/eslint-plugin@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/parser@6.18.1',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tslog@4.9.2',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/scope-manager@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/type-utils@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/utils@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/visitor-keys@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ts-api-utils@1.0.3',
npm WARN EBADENGINE   required: { node: '>=16.13.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/scope-manager@6.18.1',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@6.18.1',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/visitor-keys@6.18.1',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@typescript-eslint/types@6.15.0',
npm WARN EBADENGINE   required: { node: '^16.0.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'find-my-way@7.7.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@bcherny/json-schema-ref-parser@10.0.5-fork',
npm WARN EBADENGINE   required: { node: '>= 16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'on-exit-leak-free@2.1.2',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN deprecated superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)

> @citrineos/base@1.0.0 prepublish
> npx eslint ./src


Oops! Something went wrong! :(

ESLint: 8.56.0

/home/agardiol/dev/citrineos-core/00_Base/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js:41
                    const name = member.id?.name ?? null;
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/agardiol/dev/citrineos-core/00_Base/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js:6:56)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 2
npm ERR! path /home/agardiol/dev/citrineos-core/00_Base
npm ERR! command failed
npm ERR! command sh -c npx eslint ./src

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agardiol/.npm/_logs/2024-01-09T10_30_30_532Z-debug-0.log
Error executing npm install
```

**To Reproduce**
1.     Clone fresh repo
2.     Follow install instructions
3.     See error

**Expected behavior**
Install

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 64bits

**NPM log:**
[2024-01-09T10_30_30_532Z-debug-0.log](https://github.com/citrineos/citrineos/files/13872702/2024-01-09T10_30_30_532Z-debug-0.log)

**Comment by agardiol** [comment]
Hi @thanaParis 
Thanks, you are right. My update of node to v20 failed and I did not see that.
I was now able to run the install process.
Unfortunately, I am not able to connect to http://localhost:8055/ (connection reset by the server) even if the directus docker container is running.

**Comment by thanaParis** [comment]
@agardiol I was unable to recreate this error on Windows or Mac. As a sanity check, could you try [the new rc-1.0.0 branch](https://github.com/citrineos/citrineos-core/tree/rc-1.0.0) and tell me if you still have this issue?
